# Site settings
title: 
email: 
description: > # this means to ignore newlines until "baseurl:"
  Website
baseurl: ""
url: "" # the base hostname & protocol for your site, e.g. http://example.com
img_path: ""
linkedin: ""
github: ""
resume_pdf: ""

# Build settings
livereload: true
markdown: kramdown
plugins:
  - jekyll-haml
sass:
  sass_dir: assets/css
  style: compressed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
